import { Title } from './helper/DocumentTitle'
import styles from './Sponsoring.module.scss'

export default function About({ title }) {
  Title(title)
let content = `
<p style="line-height:1.3900000000000001;margin-bottom:8pt;margin-top:0pt;text-align:center;" dir="ltr"><span style="background-color:transparent;color:#000000;font-family:Aptos;font-size:12pt;"><span style="font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre-wrap;"><strong>CandyZap Tournament Sponsorship!</strong></span></span></p>
<p style="line-height:1.3900000000000001;margin-bottom:8pt;margin-top:0pt;" dir="ltr"><span style="background-color:transparent;color:#000000;font-family:Aptos;font-size:12pt;"><span style="font-style:normal;font-variant:normal;font-weight:400;text-decoration:none;vertical-align:baseline;white-space:pre-wrap;">CandyZap holds a 14-day tournament where players can join and compete to achieve the highest score. The winner will receive the prize pool.</span></span></p>
<p style="line-height:1.3900000000000001;margin-bottom:8pt;margin-top:0pt;" dir="ltr"><span style="background-color:transparent;color:#000000;font-family:Aptos;font-size:12pt;"><span style="font-style:normal;font-variant:normal;font-weight:400;text-decoration:none;vertical-align:baseline;white-space:pre-wrap;">All sponsorship funds go into a pool prize of LYX tokens from the LUKSO blockchain. Winners are selected based on high-scoring games twice monthly.&nbsp;</span></span></p>
<p style="line-height:1.3900000000000001;margin-bottom:8pt;margin-top:0pt;" dir="ltr"><span style="background-color:transparent;color:#000000;font-family:Aptos;font-size:12pt;"><span style="font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre-wrap;"><strong>Benefits of sponsoring a tournament</strong></span></span></p>
<p style="line-height:1.3900000000000001;margin-bottom:12pt;margin-top:12pt;" dir="ltr"><span style="background-color:transparent;color:#000000;font-family:Aptos;font-size:12pt;"><span style="font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre-wrap;"><strong>Increased brand awareness:&nbsp;</strong></span><span style="font-style:normal;font-variant:normal;font-weight:400;text-decoration:none;vertical-align:baseline;white-space:pre-wrap;">By sponsoring a tournament, your brand will be seen by a large number of CandyZap players, which could help to increase brand awareness and recognition.</span></span></p>
<p style="line-height:1.3900000000000001;margin-bottom:12pt;margin-top:12pt;" dir="ltr"><span style="background-color:transparent;color:#000000;font-family:Aptos;font-size:12pt;"><span style="font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre-wrap;"><strong>Targeted marketing:&nbsp;</strong></span><span style="font-style:normal;font-variant:normal;font-weight:400;text-decoration:none;vertical-align:baseline;white-space:pre-wrap;">CandyZap players are likely to be interested in blockchain gaming and NFTs, which could be a good target audience for your brand.</span></span></p>
<p style="line-height:1.3900000000000001;margin-bottom:12pt;margin-top:12pt;" dir="ltr"><span style="background-color:transparent;color:#000000;font-family:Aptos;font-size:12pt;"><span style="font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre-wrap;"><strong>Community engagement:&nbsp;</strong></span><span style="font-style:normal;font-variant:normal;font-weight:400;text-decoration:none;vertical-align:baseline;white-space:pre-wrap;">Sponsoring a tournament can be a great way to engage with the CandyZap community and build relationships with potential customers.</span></span></p>
<p style="line-height:1.3900000000000001;margin-bottom:12pt;margin-top:12pt;" dir="ltr"><span style="background-color:transparent;color:#000000;font-family:Aptos;font-size:12pt;"><span style="font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre-wrap;"><strong>Positive association:&nbsp;</strong></span><span style="font-style:normal;font-variant:normal;font-weight:400;text-decoration:none;vertical-align:baseline;white-space:pre-wrap;">By sponsoring a tournament, you are associating your brand with a fun and exciting event. This can create a positive association with your brand in the minds of consumers.</span></span></p>
<p style="line-height:1.3900000000000001;margin-bottom:12pt;margin-top:12pt;" dir="ltr"><span style="background-color:transparent;color:#000000;font-family:Aptos;font-size:12pt;"><span style="font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre-wrap;"><strong>Access to LYX tokens:&nbsp;</strong></span><span style="font-style:normal;font-variant:normal;font-weight:400;text-decoration:none;vertical-align:baseline;white-space:pre-wrap;">Some of the sponsorship funds go into the prize pool of LYX tokens. Depending on the sponsorship tier, you may receive some of these tokens.</span></span><br><span style="background-color:transparent;color:#000000;font-family:Aptos;font-size:12pt;"><span style="font-style:normal;font-variant:normal;font-weight:400;text-decoration:none;vertical-align:baseline;white-space:pre-wrap;">Overall, sponsoring a CandyZap tournament could be a great way to increase brand awareness, target marketing, engage with the community, and create a positive association with your brand.</span></span></p>
<p>&nbsp;</p>
<p style="line-height:1.3900000000000001;margin-bottom:8pt;margin-top:0pt;" dir="ltr"><span style="background-color:transparent;color:#000000;font-family:Aptos;font-size:12pt;"><span style="font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre-wrap;"><strong>Terms</strong></span></span></p>
<p style="line-height:1.3900000000000001;margin-bottom:8pt;margin-top:0pt;" dir="ltr"><span style="background-color:transparent;color:#000000;font-family:Aptos;font-size:12pt;"><span style="font-style:normal;font-variant:normal;font-weight:400;text-decoration:none;vertical-align:baseline;white-space:pre-wrap;">All Sponsors must provide the pool prize and management fee in $LYX&nbsp; tokens unless a different token is agreed upon before the assigned tournament starts.&nbsp;</span></span></p>
<p style="line-height:1.3900000000000001;margin-bottom:8pt;margin-top:0pt;" dir="ltr"><span style="background-color:transparent;color:#000000;font-family:Aptos;font-size:12pt;"><span style="font-style:normal;font-variant:normal;font-weight:400;text-decoration:none;vertical-align:baseline;white-space:pre-wrap;">THERE ARE 3 SPONSORSHIP PACKAGES</span></span></p>
<p style="line-height:1.3900000000000001;margin-bottom:0pt;margin-top:0pt;" dir="ltr"><span style="background-color:transparent;color:#000000;font-family:Aptos;font-size:12pt;"><span style="font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre-wrap;"><strong>Pink Package: Tournament Prize&nbsp;</strong></span></span><span style="background-color:transparent;color:#ff0000;font-family:Aptos;font-size:11pt;"><span style="font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre-wrap;"><strong>15 $LYX</strong></span></span></p>
<p style="line-height:1.3900000000000001;margin-bottom:0pt;margin-top:0pt;" dir="ltr"><span style="background-color:transparent;color:#000000;font-family:Aptos;font-size:11pt;"><span style="font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre-wrap;"><strong>Includes:</strong></span></span></p>
<ul style="margin-bottom:0;margin-top:0;padding-inline-start:48px;">
    <li style="background-color:transparent;color:#000000;font-family:Aptos;font-size:12pt;font-style:normal;font-variant:normal;font-weight:400;list-style-type:disc;text-decoration:none;vertical-align:baseline;white-space:pre;" dir="ltr" aria-level="1"><span style="background-color:transparent;color:#000000;font-family:Aptos;font-size:12pt;"><span style="font-style:normal;font-variant:normal;font-weight:400;text-decoration:none;vertical-align:baseline;white-space:pre-wrap;">Naming Rights of the tournament. (Example: The&nbsp;</span><i><span style="font-variant:normal;font-weight:400;text-decoration:none;vertical-align:baseline;white-space:pre-wrap;">XYZ</span></i><span style="font-style:normal;font-variant:normal;font-weight:400;text-decoration:none;vertical-align:baseline;white-space:pre-wrap;"> company “SweetMatch” game tournament.)</span></span></li>
    <li style="background-color:transparent;color:#000000;font-family:Aptos;font-size:12pt;font-style:normal;font-variant:normal;font-weight:400;list-style-type:disc;text-decoration:none;vertical-align:baseline;white-space:pre;" dir="ltr" aria-level="1"><span style="background-color:transparent;color:#000000;font-family:Aptos;font-size:12pt;"><span style="font-style:normal;font-variant:normal;font-weight:400;text-decoration:none;vertical-align:baseline;white-space:pre-wrap;">3 Tweets/Mentions on the X platform.</span></span></li>
    <li style="background-color:transparent;color:#000000;font-family:Aptos;font-size:12pt;font-style:normal;font-variant:normal;font-weight:400;list-style-type:disc;text-decoration:none;vertical-align:baseline;white-space:pre;" dir="ltr" aria-level="1"><span style="background-color:transparent;color:#000000;font-family:Aptos;font-size:12pt;"><span style="font-style:normal;font-variant:normal;font-weight:400;text-decoration:none;vertical-align:baseline;white-space:pre-wrap;">Follow-up data i.e. how many players participated.</span></span></li>
    <li style="background-color:transparent;color:#000000;font-family:Aptos;font-size:12pt;font-style:normal;font-variant:normal;font-weight:400;list-style-type:disc;text-decoration:none;vertical-align:baseline;white-space:pre;" dir="ltr" aria-level="1"><span style="background-color:transparent;color:#000000;font-family:Aptos;font-size:12pt;"><span style="font-style:normal;font-variant:normal;font-weight:400;text-decoration:none;vertical-align:baseline;white-space:pre-wrap;">Banner on the CandyZap home page.</span></span></li>
</ul>
<p style="line-height:1.3900000000000001;margin-bottom:0pt;margin-top:0pt;" dir="ltr"><span style="background-color:transparent;color:#ff0000;font-family:Aptos;font-size:12pt;"><span style="font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre-wrap;"><strong>Pink Tournament Management Fee **15 $LYX**&nbsp;</strong></span></span></p>
<p style="line-height:1.3900000000000001;margin-bottom:0pt;margin-top:0pt;" dir="ltr"><span style="background-color:transparent;color:#ff0000;font-family:Aptos;font-size:12pt;"><span style="font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre-wrap;"><strong>Total Sponsorship</strong></span></span></p>
<p style="line-height:1.3900000000000001;margin-bottom:0pt;margin-top:0pt;" dir="ltr"><span style="background-color:transparent;color:#ff0000;font-family:Aptos;font-size:12pt;"><span style="font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre-wrap;"><strong>30 $LYX Tokens</strong></span></span></p>
<p style="line-height:1.3900000000000001;margin-bottom:0pt;margin-top:0pt;" dir="ltr"><span style="background-color:transparent;color:#000000;font-family:Aptos;font-size:12pt;"><span style="font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre-wrap;"><strong>________________________________________________________________</strong></span></span></p>
<p style="line-height:1.3900000000000001;margin-bottom:0pt;margin-top:0pt;" dir="ltr"><span style="background-color:transparent;color:#000000;font-family:Aptos;font-size:12pt;"><span style="font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre-wrap;"><strong>Booster Package: Tournament Prize</strong></span></span><span style="background-color:transparent;color:#ff0000;font-family:Aptos;font-size:11pt;"><span style="font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre-wrap;"><strong> 40 $LYX</strong></span></span></p>
<p style="line-height:1.3900000000000001;margin-bottom:0pt;margin-top:0pt;" dir="ltr"><span style="background-color:transparent;color:#000000;font-family:Aptos;font-size:11pt;"><span style="font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre-wrap;"><strong>Includes:</strong></span></span></p>
<ul style="margin-bottom:0;margin-top:0;padding-inline-start:48px;">
    <li style="background-color:transparent;color:#000000;font-family:Aptos;font-size:12pt;font-style:normal;font-variant:normal;font-weight:400;list-style-type:disc;text-decoration:none;vertical-align:baseline;white-space:pre;" dir="ltr" aria-level="1"><span style="background-color:transparent;color:#000000;font-family:Aptos;font-size:12pt;"><span style="font-style:normal;font-variant:normal;font-weight:400;text-decoration:none;vertical-align:baseline;white-space:pre-wrap;">Character / Icon branding in the “SweetMatch” game</span></span></li>
    <li style="background-color:transparent;color:#000000;font-family:Aptos;font-size:12pt;font-style:normal;font-variant:normal;font-weight:400;list-style-type:disc;text-decoration:none;vertical-align:baseline;white-space:pre;" dir="ltr" aria-level="1"><span style="background-color:transparent;color:#000000;font-family:Aptos;font-size:12pt;"><span style="font-style:normal;font-variant:normal;font-weight:400;text-decoration:none;vertical-align:baseline;white-space:pre-wrap;">Naming Rights of the tournament. (Example: The&nbsp;</span><i><span style="font-variant:normal;font-weight:400;text-decoration:none;vertical-align:baseline;white-space:pre-wrap;">XYZ</span></i><span style="font-style:normal;font-variant:normal;font-weight:400;text-decoration:none;vertical-align:baseline;white-space:pre-wrap;"> company “SweetMatch” game tournament.)</span></span></li>
    <li style="background-color:transparent;color:#000000;font-family:Aptos;font-size:12pt;font-style:normal;font-variant:normal;font-weight:400;list-style-type:disc;text-decoration:none;vertical-align:baseline;white-space:pre;" dir="ltr" aria-level="1"><span style="background-color:transparent;color:#000000;font-family:Aptos;font-size:12pt;"><span style="font-style:normal;font-variant:normal;font-weight:400;text-decoration:none;vertical-align:baseline;white-space:pre-wrap;">3 tweets/mentions on the X platform.</span></span></li>
    <li style="background-color:transparent;color:#000000;font-family:Aptos;font-size:12pt;font-style:normal;font-variant:normal;font-weight:400;list-style-type:disc;text-decoration:none;vertical-align:baseline;white-space:pre;" dir="ltr" aria-level="1"><span style="background-color:transparent;color:#000000;font-family:Aptos;font-size:12pt;"><span style="font-style:normal;font-variant:normal;font-weight:400;text-decoration:none;vertical-align:baseline;white-space:pre-wrap;">Follow-up data i.e. how many players participated.</span></span></li>
    <li style="background-color:transparent;color:#000000;font-family:Aptos;font-size:12pt;font-style:normal;font-variant:normal;font-weight:400;list-style-type:disc;text-decoration:none;vertical-align:baseline;white-space:pre;" dir="ltr" aria-level="1"><span style="background-color:transparent;color:#000000;font-family:Aptos;font-size:12pt;"><span style="font-style:normal;font-variant:normal;font-weight:400;text-decoration:none;vertical-align:baseline;white-space:pre-wrap;">Banner on the CandyZap home page.</span></span></li>
    <li style="background-color:transparent;color:#000000;font-family:Aptos;font-size:12pt;font-style:normal;font-variant:normal;font-weight:400;list-style-type:disc;text-decoration:none;vertical-align:baseline;white-space:pre;" dir="ltr" aria-level="1"><span style="background-color:transparent;color:#000000;font-family:Aptos;font-size:12pt;"><span style="font-style:normal;font-variant:normal;font-weight:400;text-decoration:none;vertical-align:baseline;white-space:pre-wrap;">Banners, logos, or artwork on all tweets/mentions</span></span></li>
</ul>
<p style="line-height:1.3900000000000001;margin-bottom:0pt;margin-top:0pt;" dir="ltr"><span style="background-color:transparent;color:#ff0000;font-family:Aptos;font-size:12pt;"><span style="font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre-wrap;"><strong>Booster Package Tournament Management Fee **20 $LYX**</strong></span></span></p>
<p style="line-height:1.3900000000000001;margin-bottom:0pt;margin-top:0pt;" dir="ltr"><span style="background-color:transparent;color:#ff0000;font-family:Aptos;font-size:12pt;"><span style="font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre-wrap;"><strong>Total Sponsorship</strong></span></span></p>
<p style="line-height:1.3900000000000001;margin-bottom:0pt;margin-top:0pt;" dir="ltr"><span style="background-color:transparent;color:#ff0000;font-family:Aptos;font-size:12pt;"><span style="font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre-wrap;"><strong>60 $LYX Tokens</strong></span></span></p>
<p>&nbsp;</p>
<p style="line-height:1.3900000000000001;margin-bottom:0pt;margin-top:0pt;" dir="ltr"><span style="background-color:transparent;color:#000000;font-family:Aptos;font-size:12pt;"><span style="font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre-wrap;"><strong>__________________________________________________________________</strong></span></span></p>
<p style="line-height:1.3900000000000001;margin-bottom:0pt;margin-top:0pt;" dir="ltr"><span style="background-color:transparent;color:#000000;font-family:Aptos;font-size:12pt;"><span style="font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre-wrap;"><strong>Sweet Delux Package: Tournament Prize&nbsp;</strong></span></span><span style="background-color:transparent;color:#ff0000;font-family:Aptos;font-size:12pt;"><span style="font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre-wrap;"><strong>100 $LYX</strong></span></span></p>
<p style="line-height:1.3900000000000001;margin-bottom:0pt;margin-top:0pt;" dir="ltr"><span style="background-color:transparent;color:#000000;font-family:Aptos;font-size:11pt;"><span style="font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre-wrap;"><strong>Includes:</strong></span></span></p>
<ul style="margin-bottom:0;margin-top:0;padding-inline-start:48px;">
    <li style="background-color:transparent;color:#000000;font-family:Aptos;font-size:12pt;font-style:normal;font-variant:normal;font-weight:400;list-style-type:disc;text-decoration:none;vertical-align:baseline;white-space:pre;" dir="ltr" aria-level="1"><span style="background-color:transparent;color:#000000;font-family:Aptos;font-size:12pt;"><span style="font-style:normal;font-variant:normal;font-weight:400;text-decoration:none;vertical-align:baseline;white-space:pre-wrap;">Character / Icon branding in the “SweetMatch” game</span></span></li>
    <li style="background-color:transparent;color:#000000;font-family:Aptos;font-size:12pt;font-style:normal;font-variant:normal;font-weight:400;list-style-type:disc;text-decoration:none;vertical-align:baseline;white-space:pre;" dir="ltr" aria-level="1"><span style="background-color:transparent;color:#000000;font-family:Aptos;font-size:12pt;"><span style="font-style:normal;font-variant:normal;font-weight:400;text-decoration:none;vertical-align:baseline;white-space:pre-wrap;">Option to use your company’s or developer’s token as the Tournament prize</span></span></li>
    <li style="background-color:transparent;color:#000000;font-family:Aptos;font-size:12pt;font-style:normal;font-variant:normal;font-weight:400;list-style-type:disc;text-decoration:none;vertical-align:baseline;white-space:pre;" dir="ltr" aria-level="1"><span style="background-color:transparent;color:#000000;font-family:Aptos;font-size:12pt;"><span style="font-style:normal;font-variant:normal;font-weight:400;text-decoration:none;vertical-align:baseline;white-space:pre-wrap;">Naming Rights of the tournament. (Example: The&nbsp;</span><i><span style="font-variant:normal;font-weight:400;text-decoration:none;vertical-align:baseline;white-space:pre-wrap;">XYZ</span></i><span style="font-style:normal;font-variant:normal;font-weight:400;text-decoration:none;vertical-align:baseline;white-space:pre-wrap;"> company “SweetMatch” game tournament.)</span></span></li>
    <li style="background-color:transparent;color:#000000;font-family:Aptos;font-size:12pt;font-style:normal;font-variant:normal;font-weight:400;list-style-type:disc;text-decoration:none;vertical-align:baseline;white-space:pre;" dir="ltr" aria-level="1"><span style="background-color:transparent;color:#000000;font-family:Aptos;font-size:12pt;"><span style="font-style:normal;font-variant:normal;font-weight:400;text-decoration:none;vertical-align:baseline;white-space:pre-wrap;">3 tweets/mentions on the X platform.</span></span></li>
    <li style="background-color:transparent;color:#000000;font-family:Aptos;font-size:12pt;font-style:normal;font-variant:normal;font-weight:400;list-style-type:disc;text-decoration:none;vertical-align:baseline;white-space:pre;" dir="ltr" aria-level="1"><span style="background-color:transparent;color:#000000;font-family:Aptos;font-size:12pt;"><span style="font-style:normal;font-variant:normal;font-weight:400;text-decoration:none;vertical-align:baseline;white-space:pre-wrap;">Follow-up data i.e. how many players participated.</span></span></li>
    <li style="background-color:transparent;color:#000000;font-family:Aptos;font-size:12pt;font-style:normal;font-variant:normal;font-weight:400;list-style-type:disc;text-decoration:none;vertical-align:baseline;white-space:pre;" dir="ltr" aria-level="1"><span style="background-color:transparent;color:#000000;font-family:Aptos;font-size:12pt;"><span style="font-style:normal;font-variant:normal;font-weight:400;text-decoration:none;vertical-align:baseline;white-space:pre-wrap;">Banner on the CandyZap home page.</span></span></li>
    <li style="background-color:transparent;color:#000000;font-family:Aptos;font-size:12pt;font-style:normal;font-variant:normal;font-weight:400;list-style-type:disc;text-decoration:none;vertical-align:baseline;white-space:pre;" dir="ltr" aria-level="1"><span style="background-color:transparent;color:#000000;font-family:Aptos;font-size:12pt;"><span style="font-style:normal;font-variant:normal;font-weight:400;text-decoration:none;vertical-align:baseline;white-space:pre-wrap;">Banners, logos, or artwork on all tweets/mentions</span></span></li>
</ul>
<p style="line-height:1.3900000000000001;margin-bottom:0pt;margin-top:0pt;" dir="ltr"><span style="background-color:transparent;color:#ff0000;font-family:Aptos;font-size:12pt;"><span style="font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre-wrap;"><strong>Sweet Delux Package Tournament Management Fee **45 $LYX**</strong></span></span></p>
<p style="line-height:1.3900000000000001;margin-bottom:0pt;margin-top:0pt;" dir="ltr"><span style="background-color:transparent;color:#ff0000;font-family:Aptos;font-size:12pt;"><span style="font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre-wrap;"><strong>Total Sponsorship</strong></span></span></p>
<p style="line-height:1.3900000000000001;margin-bottom:0pt;margin-top:0pt;" dir="ltr"><span style="background-color:transparent;color:#ff0000;font-family:Aptos;font-size:12pt;"><span style="font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre-wrap;"><strong>145 $LYX&nbsp;</strong></span></span></p>
<ul style="margin-bottom:0;margin-top:0;padding-inline-start:48px;">
    <li style="background-color:transparent;color:#000000;font-family:Aptos;font-size:12pt;font-style:normal;font-variant:normal;font-weight:400;list-style-type:disc;text-decoration:none;vertical-align:baseline;white-space:pre;" dir="ltr" aria-level="1"><span style="background-color:transparent;color:#000000;font-family:Aptos;font-size:12pt;"><span style="font-style:normal;font-variant:normal;font-weight:400;text-decoration:none;vertical-align:baseline;white-space:pre-wrap;">45 $LYX Booster Plan&nbsp;</span></span></li>
</ul>
<p>&nbsp;</p>
<p style="line-height:1.3900000000000001;margin-bottom:0pt;margin-top:0pt;" dir="ltr"><span style="background-color:transparent;color:#000000;font-family:Aptos;font-size:12pt;"><span style="font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre-wrap;"><strong>Note</strong></span></span></p>
<p>&nbsp;</p>
<p style="line-height:1.3900000000000001;margin-bottom:0pt;margin-top:0pt;" dir="ltr"><span style="background-color:transparent;color:#000000;font-family:Aptos;font-size:12pt;"><span style="font-style:normal;font-variant:normal;font-weight:400;text-decoration:none;vertical-align:baseline;white-space:pre-wrap;">All graphic assets for premium packages must be received at the start of the agreement. Management fees must be paid in $LYX tokens or the agreed-upon token before the tournament begins.&nbsp;</span></span></p>
<p>&nbsp;</p>
<p style="line-height:1.3900000000000001;margin-bottom:0pt;margin-top:0pt;" dir="ltr"><span style="background-color:transparent;color:#000000;font-family:Aptos;font-size:12pt;"><span style="font-style:normal;font-variant:normal;font-weight:400;text-decoration:none;vertical-align:baseline;white-space:pre-wrap;">All rights reserved by Aratta Labs.</span></span></p>
<p>&nbsp;</p>
`
  return (
    <section className={styles.section}>
      <div className={`__container ms-motion-slideUpIn ${styles['container']}`} data-width={`large`}>
        <div className={`card ms-depth-4 text-justify`}>
          <div className="card__header">Candyzap Tournament Sponsorship!</div>
          <div className="card__body" dangerouslySetInnerHTML={{__html: content}} />
        </div>
      </div>
    </section>
  )
}
